[project]
name        = "depthflow"
version     = "0.0.0"
description = "Image to 2.5D Parallax Effect Video"
authors     = [{name="Tremeschin", email="29046864+Tremeschin@users.noreply.github.com"}]
readme      = "Readme.md"
license     = "AGPL-3.0"

[tool.rye]
managed = true

[project.scripts]
depthflow = "DepthFlow.__main__:main"

[tool.hatch.build.targets.wheel]
packages = ["DepthFlow"]

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"
